#ifndef __OEAPI_CONFIG_H__
#define __OEAPI_CONFIG_H__ 1

#ifndef OEAPI_ROOT
#  define OEAPI_ROOT ""
#  undef OEAPI_DEBUG_PREFIX
#else
#  define OEAPI_DEBUG_PREFIX OEAPI_ROOT ## ":"
#endif

#define OEAPI_SHARED_DATA OEAPI_ROOT ## "SharedData"

#define OEAPI_INITCOM_MUTEX  _T(OEAPI_ROOT ## "OEAPI_INITCOM_MUTEX")
#define OEAPI_OEAPIINIT_PROGID _T(OEAPI_ROOT ## "OEAPIINITCOM.OEAPIInit")
#define OEAPI_OEAPIINITSTATE_PROGID _T(OEAPI_ROOT ## "OEAPIINITCOM.OEAPIInitState")
#define OEAPI_INITCOM_CALLBACK_CLASS _T(OEAPI_ROOT ## "OEAPIInit sink")
#define OEAPI_INITCOM_CALLBACK_NAME _T(OEAPI_ROOT ## "OEAPI")

#define OEAPI_OECOM_CALLBACK_CLASS _T(OEAPI_ROOT ## "OEAPI Callback Window sink")
#define OEAPI_OECOM_CALLBACK_NAME _T(OEAPI_ROOT ## "OEAPI")

#define OEAPI_OESTORE_CALLBACK_CLASS _T(OEAPI_ROOT ## "OEStore sink")	// manager.cpp
#define OEAPI_OESTORE_CALLBACK_NAME _T(OEAPI_ROOT ## "OEAPI")	// manager.cpp
//#define OEAPI_OESTORE_CALLBACK_NAME2 _T(OEAPI_ROOT ## "OEAPI")	// main.cpp

//#define OEAPI_WM_ONINIT  _T(OEAPI_ROOT ## "OEAPI.OnInit")

//#define OEAPI_WM_ONSHUTDOWN _T(OEAPI_ROOT ## "OEAPI.OnShutdown")

#define OEAPI_NEKTRA_KEY _T("SOFTWARE\\Nektra\\OEAPI")
#define __NKTCONCAT(a, b) a ## b
#define NKTCONCAT(a, b) __NKTCONCAT(a, b)
#define OEAPI_OECOM_PLUGINS_KEY NKTCONCAT(OEAPI_NEKTRA_KEY, _T("\\Plugins"))


#define OEAPI_INIT_EVENT_NAME _T(OEAPI_ROOT ## "OEAPI_INIT_EVENT")
#define OEAPI_INIT_EVENT_NAME_END _T(OEAPI_ROOT ## "OEAPI_INIT_EVENT_END")
#define OEAPI_SHUTDOWN_EVENT_NAME _T(OEAPI_ROOT ## "OEAPI_SHUTDOWN_EVENT")
#define OEAPI_SHUTDOWN_EVENT_NAME_END _T(OEAPI_ROOT ## "OEAPI_SHUTDOWN_EVENT_END")
#define OEAPI_AFTER_THREAD_EXIT_EVENT_NAME _T(OEAPI_ROOT ## "OEAPI_AFTER_THREAD_EXIT_EVENT")
#define OEAPI_PLUGINS_INITIALIZED_EVENT_NAME _T(OEAPI_ROOT ## "OEAPI_PLUGINS_INITIALIZED_EVENT")
#define OEAPI_MANAGER_START_EVENT_NAME _T(OEAPI_ROOT ## "OEAPI_MANAGER_START_EVENT")

//#define OEAPI_CLOSE_MESSAGE _T("OEAPI_WM_CLOSE")


#endif // __OEAPI_CONFIG_H__