#ifndef __OEAPI_CONFIG_H__
#define __OEAPI_CONFIG_H__ 1

#ifndef OEAPI_ROOT
#  define OEAPI_ROOTA ""
#  define OEAPI_ROOTW L""
#  define OEAPI_ROOT _T("")
#  undef OEAPI_DEBUG_PREFIX
#else
#  define OEAPI_DEBUG_PREFIX OEAPI_ROOT ## ":"
#endif

#define __NKTCONCAT(a, b) a ## b
#define NKTCONCAT(a, b) __NKTCONCAT(a, b)

#define OEAPI_SHARED_DATA						NKTCONCAT(OEAPI_ROOTA, "SharedData")

#define OEAPI_INITCOM_MUTEX						NKTCONCAT(OEAPI_ROOT, _T("OEAPI_INITCOM_MUTEX"))
#define OEAPI_OEAPIINIT_PROGID					NKTCONCAT(OEAPI_ROOT, _T("OEAPIINITCOM.OEAPIInit"))
#define OEAPI_OEAPIINITSTATE_PROGID				NKTCONCAT(OEAPI_ROOT, _T("OEAPIINITCOM.OEAPIInitState"))
#define OEAPI_INITCOM_CALLBACK_CLASS			NKTCONCAT(OEAPI_ROOT, _T("OEAPIInit sink"))
#define OEAPI_INITCOM_CALLBACK_NAME				NKTCONCAT(OEAPI_ROOT, _T("OEAPI"))

#define OEAPI_OECOM_CALLBACK_CLASS				NKTCONCAT(OEAPI_ROOT, _T("OEAPI Callback Window sink"))
#define OEAPI_OECOM_CALLBACK_NAME				NKTCONCAT(OEAPI_ROOT, _T("OEAPI"))

#define OEAPI_OESTORE_CALLBACK_CLASS			NKTCONCAT(OEAPI_ROOT, _T("OEStore sink"))	// manager.cpp
#define OEAPI_OESTORE_CALLBACK_NAME				NKTCONCAT(OEAPI_ROOT, _T("OEAPI"))	// manager.cpp
//#define OEAPI_OESTORE_CALLBACK_NAME2 _T(OEAPI_ROOT ## "OEAPI")	// main.cpp

//#define OEAPI_WM_ONINIT  _T(OEAPI_ROOT ## "OEAPI.OnInit")

//#define OEAPI_WM_ONSHUTDOWN _T(OEAPI_ROOT ## "OEAPI.OnShutdown")

#define OEAPI_NEKTRA_KEY _T("SOFTWARE\\Nektra\\OEAPI")
#define OEAPI_OECOM_PLUGINS_KEY					NKTCONCAT(OEAPI_NEKTRA_KEY, _T("\\Plugins"))


#define OEAPI_INIT_EVENT_NAME					NKTCONCAT(OEAPI_ROOT, _T("OEAPI_INIT_EVENT"))
#define OEAPI_INIT_EVENT_NAME_END				NKTCONCAT(OEAPI_ROOT, _T("OEAPI_INIT_EVENT_END"))
#define OEAPI_SHUTDOWN_EVENT_NAME				NKTCONCAT(OEAPI_ROOT, _T("OEAPI_SHUTDOWN_EVENT"))
#define OEAPI_SHUTDOWN_EVENT_NAME_END			NKTCONCAT(OEAPI_ROOT, _T("OEAPI_SHUTDOWN_EVENT_END"))
#define OEAPI_AFTER_THREAD_EXIT_EVENT_NAME		NKTCONCAT(OEAPI_ROOT, _T("OEAPI_AFTER_THREAD_EXIT_EVENT"))
#define OEAPI_PLUGINS_INITIALIZED_EVENT_NAME	NKTCONCAT(OEAPI_ROOT, _T("OEAPI_PLUGINS_INITIALIZED_EVENT"))
#define OEAPI_MANAGER_START_EVENT_NAME			NKTCONCAT(OEAPI_ROOT, _T("OEAPI_MANAGER_START_EVENT"))

//#define OEAPI_CLOSE_MESSAGE _T("OEAPI_WM_CLOSE")


#endif // __OEAPI_CONFIG_H__